version: '3.8'

services:
  mysql_dev:
    image: mysql:8.0.28
    container_name: gerenciador-container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: gerenciadordb
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:


